/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class calculadora1 extends javax.swing.JFrame {

   private boolean igual,inicio=true,operacion1,operacion2;
   private double a,b,z, memoria=0,resultado,valor1,valor2;
   private String valorGuardado,tipoOperaciones;
    public calculadora1() {
        initComponents();
    
    labelMemoria.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtOperacion = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        labelMemoria = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_c1 = new javax.swing.JButton();
        btn_c2 = new javax.swing.JButton();
        btn_potencia1 = new javax.swing.JButton();
        btn_porcentaje = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_10 = new javax.swing.JButton();
        btn_a = new javax.swing.JButton();
        btn_multiplicacion = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_b = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_z = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_potencia = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        btn_do = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(231, 255, 255));

        txtOperacion.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        txtOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtOperacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtResultado.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        labelMemoria.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelMemoria.setText("M");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMemoria)
                .addGap(139, 139, 139))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelMemoria)
                .addGap(14, 14, 14)
                .addComponent(txtOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 576, 380, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 368, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_c1.setBackground(new java.awt.Color(0, 0, 0));
        btn_c1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_c1.setForeground(new java.awt.Color(51, 51, 51));
        btn_c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1.png"))); // NOI18N
        btn_c1.setText("C");
        btn_c1.setBorderPainted(false);
        btn_c1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_c1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1_presion.png"))); // NOI18N
        btn_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 55, 55));

        btn_c2.setBackground(new java.awt.Color(0, 0, 0));
        btn_c2.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_c2.setForeground(new java.awt.Color(51, 51, 51));
        btn_c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1.png"))); // NOI18N
        btn_c2.setText("C");
        btn_c2.setBorderPainted(false);
        btn_c2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_c2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1_presion.png"))); // NOI18N
        btn_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c2ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 55, 55));

        btn_potencia1.setBackground(new java.awt.Color(0, 0, 0));
        btn_potencia1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_potencia1.setForeground(new java.awt.Color(51, 51, 51));
        btn_potencia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1.png"))); // NOI18N
        btn_potencia1.setText("^");
        btn_potencia1.setBorderPainted(false);
        btn_potencia1.setContentAreaFilled(false);
        btn_potencia1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_potencia1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1_presion.png"))); // NOI18N
        btn_potencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_potencia1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_potencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 55, 55));

        btn_porcentaje.setBackground(new java.awt.Color(0, 0, 0));
        btn_porcentaje.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_porcentaje.setForeground(new java.awt.Color(51, 51, 51));
        btn_porcentaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1.png"))); // NOI18N
        btn_porcentaje.setText("%");
        btn_porcentaje.setBorderPainted(false);
        btn_porcentaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_porcentaje.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1_presion.png"))); // NOI18N
        btn_porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_porcentajeActionPerformed(evt);
            }
        });
        jPanel4.add(btn_porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 55, 55));

        btn_division.setBackground(new java.awt.Color(0, 0, 0));
        btn_division.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_division.setForeground(new java.awt.Color(51, 51, 51));
        btn_division.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1.png"))); // NOI18N
        btn_division.setText("/");
        btn_division.setBorderPainted(false);
        btn_division.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_division.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1_presion.png"))); // NOI18N
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });
        jPanel4.add(btn_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 55, 55));

        btn_7.setBackground(new java.awt.Color(0, 0, 0));
        btn_7.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_7.setForeground(new java.awt.Color(51, 51, 51));
        btn_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2.png"))); // NOI18N
        btn_7.setText("7");
        btn_7.setBorderPainted(false);
        btn_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2_presion.png"))); // NOI18N
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 55, 55));

        btn_8.setBackground(new java.awt.Color(0, 0, 0));
        btn_8.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_8.setForeground(new java.awt.Color(51, 51, 51));
        btn_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2.png"))); // NOI18N
        btn_8.setText("7");
        btn_8.setBorderPainted(false);
        btn_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2_presion.png"))); // NOI18N
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 55, 55));

        btn_9.setBackground(new java.awt.Color(0, 0, 0));
        btn_9.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_9.setForeground(new java.awt.Color(51, 51, 51));
        btn_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2.png"))); // NOI18N
        btn_9.setText("8");
        btn_9.setBorderPainted(false);
        btn_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2_presion.png"))); // NOI18N
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 55, 55));

        btn_10.setBackground(new java.awt.Color(0, 0, 0));
        btn_10.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_10.setForeground(new java.awt.Color(51, 51, 51));
        btn_10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2.png"))); // NOI18N
        btn_10.setText("9");
        btn_10.setBorderPainted(false);
        btn_10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2_presion.png"))); // NOI18N
        btn_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_10ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 55, 55));

        btn_a.setBackground(new java.awt.Color(0, 0, 0));
        btn_a.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_a.setForeground(new java.awt.Color(51, 51, 51));
        btn_a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1.png"))); // NOI18N
        btn_a.setText("A");
        btn_a.setBorderPainted(false);
        btn_a.setContentAreaFilled(false);
        btn_a.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_a.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1_presion.png"))); // NOI18N
        btn_a.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                btn_aComponentAdded(evt);
            }
        });
        btn_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aMouseClicked(evt);
            }
        });
        btn_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aActionPerformed(evt);
            }
        });
        jPanel4.add(btn_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 55, 55));

        btn_multiplicacion.setBackground(new java.awt.Color(0, 0, 0));
        btn_multiplicacion.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_multiplicacion.setForeground(new java.awt.Color(51, 51, 51));
        btn_multiplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1.png"))); // NOI18N
        btn_multiplicacion.setText("X");
        btn_multiplicacion.setBorderPainted(false);
        btn_multiplicacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_multiplicacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1_presion.png"))); // NOI18N
        btn_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicacionActionPerformed(evt);
            }
        });
        jPanel4.add(btn_multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 55, 55));

        btn_resta.setBackground(new java.awt.Color(0, 0, 0));
        btn_resta.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_resta.setForeground(new java.awt.Color(51, 51, 51));
        btn_resta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1.png"))); // NOI18N
        btn_resta.setText("-");
        btn_resta.setBorderPainted(false);
        btn_resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_resta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1_presion.png"))); // NOI18N
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 55, 55));

        btn_b.setBackground(new java.awt.Color(0, 0, 0));
        btn_b.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_b.setForeground(new java.awt.Color(51, 51, 51));
        btn_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1.png"))); // NOI18N
        btn_b.setText("B");
        btn_b.setBorderPainted(false);
        btn_b.setContentAreaFilled(false);
        btn_b.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_b.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1_presion.png"))); // NOI18N
        btn_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bActionPerformed(evt);
            }
        });
        jPanel4.add(btn_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 55, 55));

        btn_6.setBackground(new java.awt.Color(0, 0, 0));
        btn_6.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_6.setForeground(new java.awt.Color(51, 51, 51));
        btn_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2.png"))); // NOI18N
        btn_6.setText("6");
        btn_6.setBorderPainted(false);
        btn_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2_presion.png"))); // NOI18N
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 55, 55));

        btn_5.setBackground(new java.awt.Color(0, 0, 0));
        btn_5.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_5.setForeground(new java.awt.Color(51, 51, 51));
        btn_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2.png"))); // NOI18N
        btn_5.setText("5");
        btn_5.setBorderPainted(false);
        btn_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2_presion.png"))); // NOI18N
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 55, 55));

        btn_4.setBackground(new java.awt.Color(0, 0, 0));
        btn_4.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_4.setForeground(new java.awt.Color(51, 51, 51));
        btn_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2.png"))); // NOI18N
        btn_4.setText("4");
        btn_4.setBorderPainted(false);
        btn_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2_presion.png"))); // NOI18N
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 55, 55));

        btn_1.setBackground(new java.awt.Color(0, 0, 0));
        btn_1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_1.setForeground(new java.awt.Color(51, 51, 51));
        btn_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2.png"))); // NOI18N
        btn_1.setText("1");
        btn_1.setBorderPainted(false);
        btn_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2_presion.png"))); // NOI18N
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 55, 55));

        btn_2.setBackground(new java.awt.Color(0, 0, 0));
        btn_2.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_2.setForeground(new java.awt.Color(51, 51, 51));
        btn_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2.png"))); // NOI18N
        btn_2.setText("2");
        btn_2.setBorderPainted(false);
        btn_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2_presion.png"))); // NOI18N
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 55, 55));

        btn_3.setBackground(new java.awt.Color(0, 0, 0));
        btn_3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_3.setForeground(new java.awt.Color(51, 51, 51));
        btn_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2.png"))); // NOI18N
        btn_3.setText("3");
        btn_3.setBorderPainted(false);
        btn_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2_presion.png"))); // NOI18N
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 55, 55));

        btn_z.setBackground(new java.awt.Color(0, 0, 0));
        btn_z.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_z.setForeground(new java.awt.Color(51, 51, 51));
        btn_z.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1.png"))); // NOI18N
        btn_z.setText("Z");
        btn_z.setBorderPainted(false);
        btn_z.setContentAreaFilled(false);
        btn_z.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_z.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1_presion.png"))); // NOI18N
        btn_z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zActionPerformed(evt);
            }
        });
        jPanel4.add(btn_z, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 55, 55));

        btn_suma.setBackground(new java.awt.Color(0, 0, 0));
        btn_suma.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_suma.setForeground(new java.awt.Color(51, 51, 51));
        btn_suma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1.png"))); // NOI18N
        btn_suma.setText("+");
        btn_suma.setBorderPainted(false);
        btn_suma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_suma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1_presion.png"))); // NOI18N
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 55, 55));

        btn_igual.setBackground(new java.awt.Color(0, 0, 0));
        btn_igual.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btn_igual.setForeground(new java.awt.Color(255, 255, 255));
        btn_igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn3.png"))); // NOI18N
        btn_igual.setText("=");
        btn_igual.setBorderPainted(false);
        btn_igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_igual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn3_presion.png"))); // NOI18N
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });
        jPanel4.add(btn_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 55, 55));

        btn_potencia.setBackground(new java.awt.Color(0, 0, 0));
        btn_potencia.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_potencia.setForeground(new java.awt.Color(51, 51, 51));
        btn_potencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1.png"))); // NOI18N
        btn_potencia.setText("«");
        btn_potencia.setBorderPainted(false);
        btn_potencia.setContentAreaFilled(false);
        btn_potencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_potencia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn1_presion.png"))); // NOI18N
        btn_potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_potenciaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_potencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 55, 55));

        jButton19.setBackground(new java.awt.Color(0, 0, 0));
        jButton19.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(51, 51, 51));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btnmtz.png"))); // NOI18N
        jButton19.setText("MTZ");
        jButton19.setBorderPainted(false);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btnmtz_presion.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 79, 50));

        btn_do.setBackground(new java.awt.Color(0, 0, 0));
        btn_do.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_do.setForeground(new java.awt.Color(51, 51, 51));
        btn_do.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2.png"))); // NOI18N
        btn_do.setText(".");
        btn_do.setBorderPainted(false);
        btn_do.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_do.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2_presion.png"))); // NOI18N
        btn_do.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doActionPerformed(evt);
            }
        });
        jPanel4.add(btn_do, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 55, 55));

        btn_0.setBackground(new java.awt.Color(0, 0, 0));
        btn_0.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_0.setForeground(new java.awt.Color(51, 51, 51));
        btn_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2.png"))); // NOI18N
        btn_0.setText("0");
        btn_0.setBorderPainted(false);
        btn_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_calculadora/btn2_presion.png"))); // NOI18N
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 55, 55));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 380, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents
// boton c 
    private void btn_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c1ActionPerformed
        txtResultado.setText("0");
        txtOperacion.setText(" ");
        inicio= true;
        
        operacion1= true;
        operacion2=true;
        igual=true;
        valor1=0;
        valor2=0;
        resultado=0;
        
    }//GEN-LAST:event_btn_c1ActionPerformed

    private void btn_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_c2ActionPerformed
// boton potencia
    private void btn_potencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_potencia1ActionPerformed
        inicio=true;
        valor1= Double.parseDouble(txtResultado.getText());
        txtOperacion.setText(valor1+"^");
        tipoOperaciones="potencia";
        operacion1= false;
        igual=true;

    }//GEN-LAST:event_btn_potencia1ActionPerformed
//boton porcentaje
    private void btn_porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_porcentajeActionPerformed
      valor2 = Double.parseDouble(txtResultado.getText());
      txtOperacion.setText(txtOperacion.getText()+txtResultado.getText());
      txtResultado.setText((valor1*valor2)/100 + " ");
      igual= true;
    }//GEN-LAST:event_btn_porcentajeActionPerformed
//boton division
    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
igual = true;
inicio = true;

try {
    // Condición variable operacion1
    if (operacion1 == true) {
        valor1 = Double.parseDouble(txtResultado.getText());
        txtOperacion.setText("");
        txtOperacion.setText(txtResultado.getText() + "/");
        operacion1 = false;
    } else {
        // Condición operacion2
        if (operacion2 == true) {
            valor2 = Double.parseDouble(txtResultado.getText());
            txtOperacion.setText(txtResultado.getText() + "/");
            operacion2 = false;
        } else {
            txtOperacion.setText(txtResultado.getText() + "/");
            Operaciones(resultado, valor2);
        }
    }
    tipoOperaciones = "/";
    
    if (valor2 ==0) {
        throw new ArithmeticException("Error: División por cero no permitida.");
    }
} catch (ArithmeticException e) {
    // Mensaje de error
    JOptionPane.showMessageDialog(null, e.getMessage());
}

    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
if (inicio==true) {
            txtResultado.setText(" ");
            txtResultado.setText("7");
      inicio=false;
        }else{
            txtResultado.setText(txtResultado.getText()+7);
        }      

    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
     

    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
if (inicio==true) {
            txtResultado.setText(" ");
            txtResultado.setText("8");
      inicio=false;
        }else{
            txtResultado.setText(txtResultado.getText()+8);
        }        
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_10ActionPerformed
if (inicio==true) {
            txtResultado.setText(" ");
            txtResultado.setText("9");
      inicio=false;
        }else{
            txtResultado.setText(txtResultado.getText()+9);
        }       
    }//GEN-LAST:event_btn_10ActionPerformed

    private void btn_aComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_btn_aComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aComponentAdded

    private void btn_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aMouseClicked
 
    }//GEN-LAST:event_btn_aMouseClicked

    private void btn_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aActionPerformed
 
        
    }//GEN-LAST:event_btn_aActionPerformed
//boton multiplicacion
    private void btn_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicacionActionPerformed
igual=true;
    inicio=true;
    //condicion variable operacion1
        if (operacion1 = true) {
            valor1=Double.parseDouble(txtResultado.getText());
            txtOperacion.setText("");
            txtOperacion.setText(txtResultado.getText()+"*");
            operacion1=false;
            
        }else{
            //condicion operacion2
             if (operacion2 = true) {
            valor2=Double.parseDouble(txtResultado.getText());
            
            txtOperacion.setText(txtResultado.getText()+"*");
            operacion2=false;
            
        }else{
            txtOperacion.setText(txtResultado.getText()+"*");
            Operaciones(resultado,valor2);
        }
        }
        tipoOperaciones="*";      
    }//GEN-LAST:event_btn_multiplicacionActionPerformed
//boton resta
    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
igual=true;
    inicio=true;
    //condicion variable operacion1
        if (operacion1 = true) {
            valor1=Double.parseDouble(txtResultado.getText());
            txtOperacion.setText("");
            txtOperacion.setText(txtResultado.getText()+"-");
            operacion1=false;
            
        }else{
            //condicion operacion2
             if (operacion2 = true) {
            valor2=Double.parseDouble(txtResultado.getText());
            
            txtOperacion.setText(txtResultado.getText()+"-");
            operacion2=false;
            
        }else{
            txtOperacion.setText(txtResultado.getText()+"-");
            Operaciones(resultado,valor2);
        }
        }
        tipoOperaciones="-";                       
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
if (inicio==true) {
            txtResultado.setText(" ");
            txtResultado.setText("6");
      inicio=false;
        }else{
            txtResultado.setText(txtResultado.getText()+6);
        }      

    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
if (inicio==true) {
            txtResultado.setText(" ");
            txtResultado.setText("5");
      inicio=false;
        }else{
            txtResultado.setText(txtResultado.getText()+5);
        }       

    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
if (inicio==true) {
            txtResultado.setText(" ");
            txtResultado.setText("4");
      inicio=false;
        }else{
            txtResultado.setText(txtResultado.getText()+4);
        }       
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        if (inicio==true) {
            txtResultado.setText(" ");
            txtResultado.setText("1");
      inicio=false;
        }else{
            txtResultado.setText(txtResultado.getText()+1);
        }
      
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
if (inicio==true) {
            txtResultado.setText(" ");
            txtResultado.setText("2");
      inicio=false;
        }else{
            txtResultado.setText(txtResultado.getText()+2);
        }      
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
if (inicio==true) {
            txtResultado.setText(" ");
            txtResultado.setText("3");
      inicio=false;
        }else{
            txtResultado.setText(txtResultado.getText()+3);
        }       
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zActionPerformed

    }//GEN-LAST:event_btn_zActionPerformed
//boton suma
    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
    igual=true;
    inicio=true;
    //condicion variable operacion1
        if (operacion1 =true) {
            valor1=Double.parseDouble(txtResultado.getText());
            txtOperacion.setText("");
            txtOperacion.setText(txtResultado.getText()+"+");
            operacion1=false;
            
        }else{
            //condicion operacion2
             if (operacion2 = true) {
            valor2=Double.parseDouble(txtResultado.getText());
            
            txtOperacion.setText(txtResultado.getText()+"+");
            operacion2=false;
            
        }else{
            txtOperacion.setText(txtResultado.getText()+"+");
            Operaciones(resultado,valor2);
        }
        }
        tipoOperaciones="+";
    }//GEN-LAST:event_btn_sumaActionPerformed
//metodo con las operaciones basicas
    private void Operaciones( double valor1, double valor2){
        switch (tipoOperaciones){
            // case con la funcion suma
            case "+":
                resultado= valor1+valor2;
                txtResultado.setText(resultado+ "");
                valor1 = Double.parseDouble(txtResultado.getText());
                break;
                
       // case con la funcion resta
            case "-":
                resultado= valor1-valor2;
                txtResultado.setText(resultado+ "");
                valor1 = Double.parseDouble(txtResultado.getText());
                break;
                
                 // case con la funcion multiplicacion
            case "*":
                resultado= valor1*valor2;
                txtResultado.setText(resultado+ "");
                valor1 = Double.parseDouble(txtResultado.getText());
                break;
                
                 // case con la funcion division
            case "/":
                if (valor2==0) {
                    txtResultado.setText("MATH ERROR");
                    break;
                    
                }else{
                 resultado= valor1/valor2;
                txtResultado.setText(resultado+ "");
                valor1 = Double.parseDouble(txtResultado.getText());
                break;   
                }
                
                // case con la funcion potencia
            case "potencia":
                resultado=Math.pow(valor1,valor2);
                txtResultado.setText(resultado+" ");
                break;
                
        }
    }
//boton igual
    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
    inicio=true;
    operacion1=true;
        if (igual=true) {
            if (tipoOperaciones==null) {
                
            }else{
                valor2 = Double.parseDouble(txtResultado.getText());
                txtOperacion.setText(txtOperacion.getText()+txtResultado.getText());
                Operaciones(valor1,valor2);
                igual=false;
            }
            
        }else{
            txtOperacion.setText("");
            Operaciones(valor1,valor2);
        }
  
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_potenciaActionPerformed
        if (txtResultado.getText().length()>=1) {
            txtResultado.setText(txtResultado.getText().substring(0,txtResultado.getText().length()-1));
            if (txtResultado.getText().length()==1) {
                txtResultado.setText("0");
                inicio=true;
                
            }
        }

    }//GEN-LAST:event_btn_potenciaActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void btn_doActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doActionPerformed
  if (txtResultado.getText().contains(".")) {
            
        }else{
            txtResultado.setText(txtResultado.getText()+".");
            inicio=false;
        }
        

     
    }//GEN-LAST:event_btn_doActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
if (inicio==true) {
            txtOperacion.setText(" ");
            txtOperacion.setText("0");
      inicio=false;
        }else{
            txtOperacion.setText(txtOperacion.getText()+0);
        }
    }//GEN-LAST:event_btn_0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_10;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_a;
    private javax.swing.JButton btn_b;
    private javax.swing.JButton btn_c1;
    private javax.swing.JButton btn_c2;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_do;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_multiplicacion;
    private javax.swing.JButton btn_porcentaje;
    private javax.swing.JButton btn_potencia;
    private javax.swing.JButton btn_potencia1;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.JButton btn_z;
    private javax.swing.JButton jButton19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelMemoria;
    private javax.swing.JLabel txtOperacion;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
